import EventKit
import Foundation
import Combine

/// Handles both EventKit calendar integration and ICS file generation.
///
/// EventKit: writes directly to the user's Calendar.app (iOS + macOS).
/// ICS: generates a standards-compliant .ics string that can be shared via
///      the system share sheet (ideal for Outlook users).
@MainActor
final class CalendarService: ObservableObject {
    private let store = EKEventStore()
    @Published private(set) var authorizationStatus: EKAuthorizationStatus = .notDetermined

    /// Identifier of the calendar the user chose in Settings for new events.
    /// When empty, events fall back to Calendar.app's default calendar.
    static let selectedCalendarIdentifierKey = "selectedCalendarIdentifier"

    init() {
        refreshStatus()
    }

    // MARK: - Authorization

    func requestAccess() async -> Bool {
        do {
            // iOS 17+ / macOS 14+ uses the newer async API
            if #available(iOS 17.0, macOS 14.0, *) {
                let granted = try await store.requestFullAccessToEvents()
                refreshStatus()
                return granted
            } else {
                return try await withCheckedThrowingContinuation { continuation in
                    store.requestAccess(to: .event) { granted, error in
                        if let error {
                            continuation.resume(throwing: error)
                        } else {
                            continuation.resume(returning: granted)
                        }
                    }
                }
            }
        } catch {
            print("[Calendar] Access request failed: \(error)")
            return false
        }
    }

    var isAuthorized: Bool {
        if #available(iOS 17.0, macOS 14.0, *) {
            return EKEventStore.authorizationStatus(for: .event) == .fullAccess
        } else {
            return EKEventStore.authorizationStatus(for: .event) == .authorized
        }
    }

    // MARK: - Calendar selection

    /// Writable event calendars, sorted by title. Requests access first if needed.
    /// Returns an empty array if access is denied.
    func loadWritableCalendars() async -> [EKCalendar] {
        if !isAuthorized {
            let granted = await requestAccess()
            guard granted else { return [] }
        }
        return store.calendars(for: .event)
            .filter { $0.allowsContentModifications }
            .sorted { $0.title.localizedCaseInsensitiveCompare($1.title) == .orderedAscending }
    }

    /// The calendar chosen in Settings, or nil if none is set / no longer exists.
    private var userSelectedCalendar: EKCalendar? {
        let id = UserDefaults.standard.string(forKey: Self.selectedCalendarIdentifierKey) ?? ""
        guard !id.isEmpty else { return nil }
        return store.calendar(withIdentifier: id)
    }

    // MARK: - EventKit: create calendar event

    /// Creates an EKEvent for the session and returns the event identifier.
    func createEvent(for session: PomodoroSession) async -> String? {
        if !isAuthorized {
            let granted = await requestAccess()
            guard granted else { return nil }
        }

        // Prefer the calendar the user picked in Settings; fall back to the
        // system default so events are never silently dropped.
        guard let calendar = userSelectedCalendar ?? store.defaultCalendarForNewEvents else { return nil }

        let event = EKEvent(eventStore: store)
        event.title = "Pomodoro Focus Session \(session.sessionNumber)"
        event.startDate = session.startDate
        event.endDate = session.endDate
        event.calendar = calendar
        event.notes = session.recap.isEmpty ? nil : session.recap

        do {
            try store.save(event, span: .thisEvent)
            return event.eventIdentifier
        } catch {
            print("[Calendar] Save event failed: \(error)")
            return nil
        }
    }

    // MARK: - ICS generation

    /// Returns a standards-compliant iCalendar string for the given session.
    /// This matches the format generated by PomoTimerSD.zsh.
    func generateICS(for session: PomodoroSession) -> String {
        let uid = "pomofocus-\(Int(session.startEpoch))-\(session.sessionNumber)@pomotimer"
        let escapedRecap = icsEscape(session.recap)

        return """
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PomoLedger//PomoLedger 1.0//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:\(uid)
DTSTART:\(session.icsStart)
DTEND:\(session.icsEnd)
SUMMARY:Pomodoro Focus Session \(session.sessionNumber)
DESCRIPTION:\(escapedRecap)
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
"""
    }

    /// Writes an ICS file to the sessions directory and returns its URL.
    func writeICSFile(for session: PomodoroSession, into directory: URL) -> URL? {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd_HHmmss"
        let filename = "focus_\(formatter.string(from: session.startDate)).ics"
        let url = directory.appendingPathComponent(filename)

        do {
            try FileManager.default.createDirectory(
                at: directory, withIntermediateDirectories: true
            )
            try generateICS(for: session).write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            print("[Calendar] Write ICS failed: \(error)")
            return nil
        }
    }

    // MARK: - Private

    private func refreshStatus() {
        authorizationStatus = EKEventStore.authorizationStatus(for: .event)
    }

    /// Escapes special characters per RFC 5545 §3.3.11.
    private func icsEscape(_ text: String) -> String {
        text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: ";", with: "\\;")
            .replacingOccurrences(of: ",", with: "\\,")
            .replacingOccurrences(of: "\n", with: "\\n")
    }
}
